### ISSUE TITLE
bug in /etc/profile.d/tqt3.sh and /etc/profile.d/tqt3.csh

### ISSUE THREAD

**Issue by Ndolam** [Thorn-Inurcide/tde-slackbuilds#11]
These files have lines using
${LIBDIRSUFFIX}
which is not set anywhere when one is logging in fresh.
On a 32 bit system, this does The Right Thing, but not so much on a 64-bit system.

(Thanks for the scripts, by the way.)

**Comment by Ndolam** [comment]
Here is one possible fix (in tqt3.SlackBuild):
replace 
cat $SRCDIR/profile.d/${PRGNAM}.sh > $PKG/etc/profile.d/${PRGNAM}.sh           
cat $SRCDIR/profile.d/${PRGNAM}.csh > $PKG/etc/profile.d/${PRGNAM}.csh         
with                                                                  
sed "s/\${LIBDIRSUFFIX}/$LIBDIRSUFFIX/g" < $SRCDIR/profile.d/${PRGNAM}.sh > $PKG/etc/profile.d/${PRGNAM}.sh
sed "s/\${LIBDIRSUFFIX}/$LIBDIRSUFFIX/g" < $SRCDIR/profile.d/${PRGNAM}.csh > $PKG/etc/profile.d/${PRGNAM}.csh

**Comment by Thorn-Inurcide** [comment]
Thank you.
Any chance you can do this and I'll merge it? My life is hectic right now with lots of moving. My pc isn't even hooked up. I'm on a phone.  If you can't I'll leave this open and get to it next month sometime.  Sorry I can't do better than that =(

**Comment by Ndolam** [comment]
Regrettably, I am a github n00b, and my attempts to do things The Right Way for another project have met with failure.  I'll give it a try tomorrow, but I can only promise to try.

**Comment by Thorn-Inurcide** [comment]
It's ok.
You should be able to change the file and drag and drop now. Just make sure to drop it into the profiled folder of tqt3. Should be that simple..should being the keyword there....

**Comment by Ndolam** [comment]
When you wrote "the profiled folder" I assume you meant profile.d.
But the fix is in tqt3.SlackBuild.  Is it still OK with you for me to copy that in?

**Comment by Thorn-Inurcide** [comment]
Yeah and I had that confused. Go ahead and fix

**Comment by Ndolam** [comment]
"You should be able to change the file and drag and drop now."
Well, as I said, I'm a github n00b, and trying to change the file by dragging and dropping or by using the "upload files" button fails.
I don't know whether you need to do something (else) at your end, or whether I just need to find some docs that explain github using very simple step-by-step instructions.
If the former, let me know.  Otherwise, this can wait until you are back up and running at 100% power.  However, if you meant "drag and drop" to this message, here it is.  I had to rename it to .txt to make github happy, but there you go.

[tqt3.SlackBuild.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/247294/tqt3.SlackBuild.txt)

**Comment by Thorn-Inurcide** [comment]
Hmm I'll leave this open and submit your changes for you. And thank you. I
don't know about other people's repos but I just git pull the repo then
after making changes I run
Git add -A
Git commit -m 'update/changed explanation
Git push thereponame master
And that pushes to master branch

**Comment by Ndolam** [comment]
"You should be able to change the file and drag and drop now."
Well, as I said, I'm a github n00b, and trying to change the file by dragging and dropping or by using the "upload files" button fails.
I don't know whether you need to do something (else) at your end, or whether I just need to find some docs that explain github using very simple step-by-step instructions.
If the former, let me know.  Otherwise, this can wait until you are back up and running at 100% power.  However, if you meant "drag and drop" to this message, here it is.  I had to rename it to .txt to make github happy, but there you go.

[tqt3.SlackBuild.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/247294/tqt3.SlackBuild.txt)

**Comment by Ndolam** [comment]
git push https://github.com/Thorn-Inurcide/tde-slackbuilds master
Username for 'https://github.com': ndolam
Password for 'https://ndolam@github.com': 
remote: Permission to Thorn-Inurcide/tde-slackbuilds.git denied to Ndolam.
fatal: unable to access 'https://github.com/Thorn-Inurcide/tde-slackbuilds/': The requested URL returned error: 403

**Comment by Thorn-Inurcide** [comment]
Got my PC hooked up for a bit and current updated, will check this out

**Comment by Thorn-Inurcide** [comment]
Added.
Thank you again.
