### ISSUE TITLE
`wget` returns true despite a failed download.

### ISSUE THREAD

**Issue by ryanpcmcquen** [Thorn-Inurcide/tde-slackbuilds#14]
Originally reported here:
https://github.com/Thorn-Inurcide/tde-slackbuilds/issues/12#issuecomment-238268373

This will fix it:
https://github.com/Thorn-Inurcide/tde-slackbuilds/pull/13

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen  got this merged, if not reopen please =]
