### ISSUE TITLE
Don't upgrade existing Slackware packages with TDE packages

### ISSUE THREAD

**Issue by Ndolam** [Thorn-Inurcide/tde-slackbuilds#16]
The following packages (at least, there may be more) replaced existing Slackware packages.
In the interest of separating KDE and TDE, I think that shouldn't happen.  Adding TDE to the names of these packages so that upgradepkg doesn't upgrade Slackware packages is one solution.  A second (probably far less preferable) is to just install the packages, since there is
no overlap in the files (I believe) between the TDE and KDE versions.
- libkipi
- gwenview
- amarok
- k3b
- libkexiv2
- libdcraw

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Hopefully start on this today, Will be doing a fresh install first

**Comment by Ndolam** [comment]
Thanks for the update.  
Let me know how it goes, or if you want a second opinion on some change.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Just wanted to let you know I've been working on this. This will probably be an all weekend project.
I'm compiling ffmpeg right now, seems to be a dep for k9copy (well the libavcodec part of it)
If so that will need to be mentioned in the description so users know they need ffmpeg first.

**Comment by Thorn-Inurcide** [comment]
Ok it looks like those are the only packages that need to be renamed.

**Comment by Ndolam** [comment]
Good catch on the ffmpeg/k9copy thing.  I always install that in a new Slaackware, so I didn't notice the problem.

Mentioning in the description is a Good Thing.  In the longer run, putting a check in the script might be a more complete solution.   Whether it wants to be in BUILD-TDE.sh, Apps/k9copy/k9copy.SlackBuild, or both is not 100% clear to me.

**Comment by Thorn-Inurcide** [comment]
Yeah ffmpeg is usually the second thing I install right after geany.
If we do a check for ffmpeg and it is not there the build will have to be skipped entirely (which we can do) but we should still mention that it requires it so people know in advance why it got skipped.

I'm thinking any build skipping will need to be done in BUILD-TDE.sh
just use sed to remove the things that won't/don't need to build.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I have this corrected locally, I just cleaned my PC up and am re-running the BUILD-TDE.sh just to be sure. Also have mp4v2 renamed to libmp4v2.
I will push all of this after I verify the changes I made are working.

I still need to solve the other issue. I will resume this later. Have some things to go do soon today.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 

ok now gwenview is trying to build against the kde4 libs, so i have to direct the slackbuilds to the tde ones, this just got delayed. until i get home

**Comment by Thorn-Inurcide** [comment]
@Ray-V @Ndolam @ryanpcmcquen 
I cannot get gwenview to find libkipi in in /opt/trinity and build against it, it defaults to Slackware's shipped version which it fails to compile against. I removed Slackware's libkipi and it built but with an auto detect of --without-kipi. I've been trying to force it to check in the proper place, which it should be doing already anyways but is refusing to. Any ideas? Trying to think of a way to force it look just for libkipi 

--with-extra-libs=
--with-extra-includes=

I tried using these from the configure script in gwenview but got nowhere

**Comment by Thorn-Inurcide** [comment]
I renamed libkipi to tdelibkipi but just the package, it is still installed into /opt/trinity/lib64 as libkipi

**Comment by Thorn-Inurcide** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/10385564/17645585/d8c350ac-6177-11e6-82e0-fc46b06d72c4.png)

**Comment by Thorn-Inurcide** [comment]
Problem solved with packages being overwritten, but libkipi problem remains. will push this for now, with --without-kipi passed in tdegwenview I suppose while a fix is found =[

**Comment by Thorn-Inurcide** [comment]
Closing this issue and opening a new one
