### ISSUE TITLE
gwenview not finding libkipi

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#19]
Cannot get gwenview to use libkipi in /opt/trinity
Have had to pass --without-kipi to the SlackBuild to keep it from trying to compile against the KDE4
libkipi which fails.

**Comment by Ndolam** [comment]
Hmmm... if only the TDE upstream had renamed kipi to tipi, this probably would not be an issue.

On my system, gwenview happily compiled, but that was probably ("certainly"?) because the Slackware libkipi had been deleted at the time I compiled.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Yes it compiled for me after I deleted it as well
Maybe we can submit this renaming suggestion to upstream

**Comment by Thorn-Inurcide** [comment]
I'd really like this to compile against tde's libkipi if at all possible, so a user who wanted those features in gwenview could have them

**Comment by Ray-V** [comment]
Line 68 of get-source.sh is:
               `SLKLDFLAGS="-L/usr/lib64"`

I can see why it might be there, but it's causing ld to look there first and find the KDE4 libkipi.

`               SLKLDFLAGS=""`
works for gwenview, but I don't know what affect it might have on other builds [haven't checked].

Safest bet is probably ..
`    x86_64)`
               `SLKLDFLAGS="-L$INSTALL_TDE/lib$LIBDIRSUFFIX -L/usr/lib64"`
which also works for gwenview.

.. and for the other ARCHs:
              ` SLKLDFLAGS="-L$INSTALL_TDE/lib$LIBDIRSUFFIX"`

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Thank you!
