### ISSUE TITLE
mp4v2 is not where the build script thinks it is

### ISSUE THREAD

**Issue by Ndolam** [Thorn-Inurcide/tde-slackbuilds#20]
I tried building (most of) TDE last night.  It got to where it was going to build mp4v2 and then
couldn't d/l the .tar.bz2 file.  Today that file is at https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2

Cheers.

**Comment by Ndolam** [comment]
P.S., just for the info of anyone reading...  I compiled almost all of 14.0.4 with the build scripts, and except for the mp4v2 issue, it all went well.

**Comment by Thorn-Inurcide** [comment]
Hi, thanks for info. I just moved and don't have internet right now so there isn't much I can do with this at the moment. After I'm caught up on bills and am settled in I will get internet. Right now I have to much other things to buy. Sorry about this.

**Comment by Ndolam** [comment]
No biggie.  Easy enough to fix for anyone using your build scripts, I just thought I'd mention it.
Cheers.

**Comment by Thorn-Inurcide** [comment]
I appreciate it man.

**Comment by Thorn-Inurcide** [comment]
@Ndolam  this is fixed so will close issue, thank you
