### ISSUE TITLE
New TDEVERSION variable

### ISSUE THREAD

**Issue by Ray-V** [Thorn-Inurcide/tde-slackbuilds#21]
Instead of updating the build scripts with the TDE version every time it changes, let's future-proof them with a new variable in the dialog build script - say TDEVERSION.

I've updated my copy and included the new mp4v2 URL with this script which is commented to show what I've done.

A complete 64-bit build was successful with locally stored sources and also checked out OK with a sample source download from each of Core/Deps/Apps/Misc/Libs categories.

I think libcaldav should be an optional dependency if it's only required for korganizer.
In case you don't agree, I've set it as a separate patch in this script for easy removal.

[add-TDEVERSION.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/615014/add-TDEVERSION.gz)

**Comment by Thorn-Inurcide** [comment]
Yeah it can be optional. especially if that's all it's needed for. I still
can't do crap with this moving to another apartment soon due to problems
with this one and haven't got internet because of it yet. that all sounds
great to me though. you still have push access also so if it's all
compiling right go ahead and make the changes and push it to the repo . I
won't have any idea how long I'm going to be out of this until I move
again. I find tomorrow when that's going to be.

**Comment by Ray-V** [comment]
Done.

Also added a check for libcaldav installed or being built and if it is, included in tdepim build.

Changes:
[diffs.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/629423/diffs.gz)

**Comment by Thorn-Inurcide** [comment]
Thanks man. I appreciate it, and I'm sure others do to. I'm moving to new
apartment Saturday so hopefully I'll have internet soon

On Sunday, December 4, 2016, Ray-V <notifications@github.com> wrote:
> Done.
>
> Also added a check for libcaldav installed or being built and if it is,
included in tdepim build.
>
> Changes:
> diffs.gz
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/0f67pbk7x7jS1QS7PIQtZPd-Ms_2RFCIOUOcVNRi5nrmkvhNQI7x0AYTyK5AIiP0tQU3rlyGSz5QxOHx-G6I0dObkN3tUd64t-zRdzk69jUQ8Mzv2apNakOH2prGAGRSM9EGdgJDSFBVGN3FKPT8fJi6yLJMPg=s0-d-e1-ft#https://github.com/notifications/beacon/AJ54nH6w5kNh7hxlK_RVZyyhS7OxLqj2ks5rEp_6gaJpZM4K9QAV.gif>
