### ISSUE TITLE
Updating builds to cmake

### ISSUE THREAD

**Issue by Ray-V** [Thorn-Inurcide/tde-slackbuilds#22]
I've updated some of the builds to cmake.

dolphin
Was set up for cmake in R14.0.3 source, but documentation and locales didn't build. I've added a patch to the SlackBuild and it now builds with html docs and locale data.
Removed README and slack-desc.

amarok
Patched for speex metadata support.
Tests for libmp4v2 installed, and if it's not defaults to m4a metadata support for mp4.

tdenetwork
Now defaults to re-written cmake build.
Tests for whether speex is installed, and if it is sets the speex option on.
Removed previous SB-cmake and slack-desc.

tdepim
Moved libcaldav test from BUILD-TDE.sh to the SlackBuild. I thought there were going to be more applications affected by optional builds and putting the tests in BUILD-TDE.sh would avoid having to repeat them in the SlackBuilds - but it didn't turn out that way, so I've put any test for options in the relevant SB.

----------------
These are new for R14.0.4 [*]:

k3b[-i18n]
Straightforward, no issues.

tdegames
Carddecks are not built if the games needing them are not built.

----------------
For tdenetwork, k3b, amarok, tdegames I've put all the build options in the SlackBuilds so that it's easier to see what's included in the build, rather than having BUILD_ALL=ON/OFF and having to look in the CMakeLists.txt file to see how the options have been set.

I haven't updated tdemultimedia and tdewebdev because the cmake builds are incomplete. I'll put patching these on my TODO list.

Changes:
[diffs.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/644409/diffs.gz)

@Thorn-Inurcide If you're happy with these changes, and don't have time or internet access, I'll merge them - just let me know.

[*] won't build for R14.0.3 because that version isn't set up for cmake. Would only be a problem if anybody tried to build them for R14.0.3 which I think is not likely now that R14.0.4 has been released.

**Comment by Thorn-Inurcide** [comment]
this is awesome. I'll be able to check this out this weekend. Thanks again
for everything. You can merge them if you'd like. I'm running all over the
place right now, but will build all of this hopefully Saturday, if not then
Sunday.
I think that's all a good idea, and looks great to me

**Comment by Ray-V** [comment]
Let's leave it till Sunday then.

I've set up SBs for two more apps [abakus and filelight] that can be added.
The Apps list in BUILD-TDE.sh was getting a bit untidy so I've re-arranged it in program name order to make selecting individual builds easier.

This should patch OK:
[new-apps-diffs.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/657029/new-apps-diffs.gz)

**Comment by Thorn-Inurcide** [comment]
Ok I'm finally up and running again, (Slackware likes to not work on this Dell I made the mistake of buying.)
So everything's working and I'm online...but on a fresh install. So let me get setup and I'll go over everything.

Thanks again @Ray-V

**Comment by Ray-V** [comment]
Some more to keep you busy ..

Added Apps/{knmap,kscope,tdesudo}, and Misc/graphviz [for 'dot' for kscope] based on the SBo SlackBuild.
Modified BUILD-TDE.sh so that all the highlighted default buttons are on the right.

Added an option to tqt3 build to put TDE libs paths at the beginning of the search path - there's a help screen in BUILD-TDE.sh and the tqt3 section is commented.

[diffs-3.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/671521/diffs-3.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V  awesome lol

**Comment by Ray-V** [comment]
I wasn't happy with the result of the previous changes to tqt3 SB.

This is much better - it avoids duplication of search paths.

[tqt3-diff-4.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/671816/tqt3-diff-4.gz)

**Comment by ryanpcmcquen** [comment]
@Ray-V do you know how to bundle these as pull requests?

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
To make this easier, can you give me a tarball of your local repo that has all these changes already?
I'm ready to run tde, but i'm not sure how to take these giant diffs and apply them without breaking the patches down individually and applying them

**Comment by Ray-V** [comment]
@Thorn-Inurcide

Sure.

I set them up to be applied consecutively from the build directory.

That's:
git clone https://github.com/Thorn-Inurcide/tde-slackbuilds.git
cd tde-slackbuilds

zcat /path/to/diffs.gz | patch -p0
zcat /path/to/new-apps-diffs.gz | patch -p0
zcat /path/to/diffs-3.gz | patch -p0
zcat /path/to/tqt3-diff-4.gz | patch -p0

I've just checked it and this is the result I got - stopped short of pushing ..

[my-results.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/673331/my-results.txt)

I've checked this against the master I'm working to and it checks out ok, so should be good to go when/if you're happy with everything.

**Comment by Thorn-Inurcide** [comment]
Awesome thanks ill do that tonight. I built from master to check out changes/updates so far and like them.
Sent using Zoho Mail


---- On Mon, 26 Dec 2016 14:12:41 -0800 notifications@github.com wrote ----

@Thorn-Inurcide

Sure.

I set them up to be applied consecutively from the build directory.

That's:
git clone https://github.com/Thorn-Inurcide/tde-slackbuilds.git
cd tde-slackbuilds

zcat /path/to/diffs.gz | patch -p0
zcat /path/to/new-apps-diffs.gz | patch -p0
zcat /path/to/diffs-3.gz | patch -p0
zcat /path/to/tqt3-diff-4.gz | patch -p0

I've just checked it and this is the result I got - stopped short of pushing ..

my-results.txt

I've checked this against the master I'm working to and it checks out ok, so should be good to go when/if you're happy with everything.

**Comment by Thorn-Inurcide** [comment]
@Ray-V  Cannot get the tqt3-diff-4 to download properly for some reason, will try again in a bit, if that doesn't work I may have to re upload itfor me, i downloaded it the other day didnt save it...

**Comment by Thorn-Inurcide** [comment]
@Ray-V  alright it finally decided to DL properly. =/ was weird.

I also added moodbar so Amarok can have moods..you know..cause this project isn't big enough yet =]

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I like, Only change I'm really making is in tdeamarok, I'm turning xine on. Amarok uses Xine-lib package as the engine and without it it doesn't play music.

**Comment by Thorn-Inurcide** [comment]
I should probbly make note of that xine-lib requirement ....

**Comment by Thorn-Inurcide** [comment]
made note of that and added a check for it instead of just having it on ON|OFF

**Comment by Thorn-Inurcide** [comment]
I guess I'll close this issue. If something comes up a new issue can be made @Ray-V
