### ISSUE TITLE
Koffice Chalk crash and imagemagick interference

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#23]
@Ray-V  @ryanpcmcquen  
I have koffice compiled on my machine, but I had to remove imagemagick to accomplish this due to undefined symbols errors at the karbon build stage. I reinstalled it on my system afterwords but Chalk crashes as soon as I try to launch it. I'm unable to --disable-imagemagick or use --without on it. I guess my option is to patch the configure script to not check for it. I think it specifically checks for magick-config.
Any ideas besides this one? (because it looks like it will be a pain)
![snapshot6](https://cloud.githubusercontent.com/assets/10385564/21514232/7bbe4304-cc88-11e6-8989-51ba2eaeb072.png)
![snapshot7](https://cloud.githubusercontent.com/assets/10385564/21514241/949f677c-cc88-11e6-92b5-bfc882e9f387.png)
![snapshot8](https://cloud.githubusercontent.com/assets/10385564/21514243/9cc63836-cc88-11e6-9ce3-8851069ce5d8.png)
![snapshot9](https://cloud.githubusercontent.com/assets/10385564/21514244/a46b62dc-cc88-11e6-8134-1871a546b774.png)

**Comment by Thorn-Inurcide** [comment]
[koffice.SlackBuild.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/675055/koffice.SlackBuild.txt)

**Comment by Ray-V** [comment]
@Thorn-Inurcide 
cc. @ryanpcmcquen 


Does this help?

Using the koffice.SB you supplied, I got this failure:
```
/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DestroyPixelWand'  
/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DrawPushPattern'  
...  
/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeLineCap'  
/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DrawEllipse'  
collect2: error: ld returned 1 exit status  
Makefile:1658: recipe for target 'karbon' failed  
```
Found this:
http://www.linuxquestions.org/questions/slackware-14/that-which-could-be-fixed-in-sbo-thread-4175532869/page14.html

Added this to the SB:
LDFLAGS="${SLKLDFLAGS} $($(which Magick++-config) --libs)" \

and it built - but haven't tested it.

**Comment by Thorn-Inurcide** [comment]
@Ray-V  thanks man, I'm compiling now

**Comment by Thorn-Inurcide** [comment]
@Ray-V  I started work on the Python bindings, hopefully have those working by the weekend, sip4-tqt was a pain, I didn't realize i had to manually add sip4_tqt to the end of the destdir VAR until i ran it as non root and checked the generated makefile. python-tqt is created an error but I think I'm going to do TQScintillia first anywas as python-tqt is looking for it. (Was following suggested build order) _

**Comment by Thorn-Inurcide** [comment]
@Ray-V  that worked and Built it, but Chalk is still crashing upon launch.
I guess I'll deal with that some other time, I'm just happy everything else in Koffice is working right now.
