### ISSUE TITLE
moodbar SlackBuild

### ISSUE THREAD

**Issue by Ray-V** [Thorn-Inurcide/tde-slackbuilds#24]
Couple of issues with moodbar.SB

The build can't find moodbar-0.1.2.tar.gz if it's already in the 'src' directory
Need to add ARCHIVE_TYPE="tar.gz" to the moodbar.SB to override the TDE default of tar.bz2

And docs are in ${PRGNAM}-${VERSION} directory

--- Misc/moodbar/moodbar.SlackBuild
+++ Misc/moodbar/moodbar.SlackBuild
@@ -30,0 +31 @@
+ARCHIVE_TYPE="tar.gz"
@@ -35,0 +37,2 @@
+cd ${PRGNAM}-${VERSION}
+
@@ -39 +41,0 @@
-cd ${PRGNAM}-${VERSION}

**Comment by Thorn-Inurcide** [comment]
Yeah the configure script wouldnt accept docdir and i completely forgot to change it in the package. I didnt even catch the downloading thing though. 
Sent using Zoho Mail


---- On Wed, 28 Dec 2016 07:37:02 -0800 notifications@github.com wrote ----

Couple of issues with moodbar.SB

The build can't find moodbar-0.1.2.tar.gz if it's already in the 'src' directory
Need to add ARCHIVE_TYPE="tar.gz" to the moodbar.SB to override the TDE default of tar.bz2

And docs are in ${PRGNAM}-${VERSION} directory

--- Misc/moodbar/moodbar.SlackBuild
+++ Misc/moodbar/moodbar.SlackBuild
@@ -30,0 +31 @@
+ARCHIVE_TYPE="tar.gz"
@@ -35,0 +37,2 @@
+cd ${PRGNAM}-${VERSION}
+
@@ -39 +41,0 @@
-cd ${PRGNAM}-${VERSION}

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Archive patch applied, and moodbar is not even installing any documentation on my end

./
install/
install/slack-desc
usr/
usr/lib64/
usr/lib64/gstreamer-0.10/
usr/lib64/gstreamer-0.10/libmoodbar.so
usr/lib64/gstreamer-0.10/libmoodbar.la
usr/bin/
usr/bin/moodbar
usr/doc/
usr/doc/moodbar-0.1.2/
usr/doc/moodbar-0.1.2/AUTHORS
usr/doc/moodbar-0.1.2/COPYING
usr/doc/moodbar-0.1.2/README
usr/doc/moodbar-0.1.2/ChangeLog
usr/doc/moodbar-0.1.2/moodbar.SlackBuild
usr/doc/moodbar-0.1.2/INSTALL
usr/doc/moodbar-0.1.2/TODO
usr/doc/moodbar-0.1.2/NEWS

**Comment by Ray-V** [comment]
usr/doc/moodbar-0.1.2/....

Those are the ones I meant - the DOCS variable just scoops up the miscellaneous stuff which is usually in the source root directory

**Comment by Thorn-Inurcide** [comment]
I'm confused lol aren't the docs supposed to be in /usr/doc/${PRGNAM}-${VERSION} where they're at?

**Comment by Thorn-Inurcide** [comment]
I installed it system-wide thats why the docs are going there.. you think I should change it to the install_tde VAR?

**Comment by Ray-V** [comment]
I didn't phrase my comment very well. Should have said 'And the miscellaneous docs should be in ${PRGNAM}-${VERSION} directory'

Pre-patch, the only entry in usr/doc/moodbar-0.1.2/ was moodbar.SlackBuild

Post-patch, as you've shown above, all the other misc docs are in that directory as well.

So, all is now OK.

**Comment by Thorn-Inurcide** [comment]
@Ray-V  alright lol I probably should have caught onto that... thanks man. I'll pay more attention to that in the future.
