### ISSUE TITLE
Compiler option

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#31]
[TDE.zip](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/680778/TDE.zip)

@Ray-V 
Added an option to choose between GCC or Clang. Wondering what you think. I added it before the tdemirror selection and the other change is at the export of the TMPVARS, only slackbuild i made the variable change to was dolphin just for quick easy testing purposes. I tried to follow your "style" as best I could. You can def tell i did the if/else part by the exports though......

If you like it i'll go ahead and start adding the variable in in the slackbuilds. I like it, and would like to be able to compile with clang or gcc, just more freedom of choice.

**Comment by Thorn-Inurcide** [comment]
tdelibs is failing to compile with clang, with use gcc on it and try the rest

**Comment by SlavekB** [comment]
Instead of manually selecting a mirror you can use redirector on mirror.ppa.trinitydesktop.org/trinity - redirector uses information from Trinity mirrorstatus and also directs users to closest mirror by GeoIP.

**Comment by Thorn-Inurcide** [comment]
@SlavekB 
Do I need to add software to Slackware to do that?

**Comment by SlavekB** [comment]
If you're building tdelibs R14.0.4, you will find useful patch or commit:

http://mirror.git.trinitydesktop.org/cgit/tde-packaging/tree/freebsd/tdelibs/files/patch-bp000-fix-ftbfs-with-clang.diff?h=r14.0.x

http://mirror.git.trinitydesktop.org/cgit/tdelibs/commit/?h=r14.0.x&id=df11fa8d

**Comment by Thorn-Inurcide** [comment]
@SlavekB 

Sweet after this compile run finishes I'll try that out, thank you

**Comment by SlavekB** [comment]
To use redirector should be enough to set:

**Comment by SlavekB** [comment]
TDE_MIRROR=mirror.ppa.trinitydesktop.org/trinity

**Comment by Thorn-Inurcide** [comment]
@SlavekB  thanks, that is great. I didn't even know anything about that..I still don't lol

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I have all the doinst.sh fixed locally, completely overlooked them after the switch to the version variable.

**Comment by Thorn-Inurcide** [comment]
@SlavekB  that patched worked thank you again

@Ray-V  
everything compiled with Clang except koffice and kaffeine. I'll force GCC in them for now and deal with it later. I have to fix my SB's again I deleted all my corrected ones by mistake. Also seemed like the script wasn't bailing on error compiles even though I had stop selected. Might have been something I did though.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Since this is the last day I'm going to have for awhile to sit here and do this, I've made all the changes already, and I will push them. I cleaned up all the SlackBuilds to have the same uniform feel to them. Added a compiler option in BUILD-TDE.sh (which you should probably look at when you get a chance to make sure I didn't screw anything up lol) things appear to be working though. I also commented out the mirrors selection part to use SlavekB's recommendation. If you feel selecting a mirror is a better way to go we can just uncomment it and put it back in, it makes no difference to me, I just wanted to try the other way, and it is working (for me).  And as always is something broke, people can just open an issue up.

**Comment by Ray-V** [comment]
@Thorn-Inurcide 
Just to let you know I haven't been ignoring you, I don't check my email regularly, and I was working on #32 [among other things].

I think options are welcome and as you say, if anything is broken, an issue can be raised.
I didn't know about the redirector either - haven't used it yet, but seems like a good idea [also good to see another presence here].

Don't be influenced by my 'style' though - it's 'get an idea' and with Google's help, 'stand on the shoulders of giants' to find a way of implementing it.

Like you though, it's back to the real world now ...

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I uninstalled my tde installation yesterday (which a huge slackpkg remove command I have saved to a txt file) and deleted all my user files, then rebuilt all of tde using clang and the redirector and all went well, until the apps dir, I think I found..5 SB's that wouldn't build using clang, so they are using gcc regardless, once I get another day to sit down here to this I hit the internet and see if I can fix it, I'm thinking there might be some option I can pass to it to make it ignore whatever is causing it to fail to build. I remeber one complaining about a "*d" which is probably a pointer that's not being called or used how clang expects it to be.
