### ISSUE TITLE
Using a functions script

### ISSUE THREAD

**Issue by Ray-V** [Thorn-Inurcide/tde-slackbuilds#34]
@Thorn-Inurcide 
Re: your comment in the CHANGELOG about making changes in one place and freeing up space in the SBs - how far do you want to go with that?

We could use 'get-source.sh' as a functions script and then call up common functions from the SBs, which would also help keep the number of files to be maintained to a minimum.

I've set up knmap.SB as an example.

get-source.sh has been modified to wrap the existing content in 'getsource () { }' and ltoolupdate.sh added as a function in 'ltoolupdate () { }' -

with other common stuff added like:
DOCS variable
the docs section after make
the makepkg section ..
just leaving stuff in the SB which can't be treated as a common routine.

If you're open to the idea, I'll look at how this could work out for the complete build.
[knmapSB_get-source.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/711045/knmapSB_get-source.tar.gz)

**Comment by Thorn-Inurcide** [comment]
Just wanted to let you know I've been down in Florida working looks like another month left of work. So I won't be able to do anything on here until that's all said and done . What I see in my emails sounds good, but I haven't been on Github to see anything yet
Sent using Zoho Mail


---- On Tue, 17 Jan 2017 05:06:46 -0800 notifications@github.com wrote ----

@Thorn-Inurcide
Re: your comment in the CHANGELOG about making changes in one place and freeing up space in the SBs - how far do you want to go with that?

We could use 'get-source.sh' as a functions script and then call up common functions from the SBs, which would also help keep the number of files to be maintained to a minimum.

I've set up knmap.SB as an example.

get-source.sh has been modified to wrap the existing content in 'getsource () { }' and ltoolupdate.sh added as a function in 'ltoolupdate () { }' -

with other common stuff added like:
DOCS variable
the docs section after make
the makepkg section ..
just leaving stuff in the SB which can't be treated as a common routine.

If you're open to the idea, I'll look at how this could work out for the complete build.
knmapSB_get-source.tar.gz

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Just got to look at this and I like it

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Thanks for everything man. Sorry haven't been  on here much , a lot going on right now. I merged your pull request. I'm on a fresh install...again... Slackware has been a real pain for me lately due to the fact it hates this piece of shit DELL computer I made the mistake of buying... =[ Likes to randomly freeze..so yeah that's annoying. Anyways I'm going to go for now, getting tired.
