### ISSUE TITLE
build dies on kvpnc

### ISSUE THREAD

**Issue by Ndolam** [Thorn-Inurcide/tde-slackbuilds#36]
Starting from scratch, on Slackware64 14.2 (with Alien Bob's multi-lib stuff) building almost everything, using the buid scripts I downloaded earlier today, I get this:
... many many lines omitted here ...

PACKAGE DESCRIPTION:
# KSquirrel is an image viewer for TDE.
#
# Image decoding is based on it's own decoders (ksquirrel-libs)
#
# With OpenGL and KIPI support.
#
# With language support for:
#
# en 
#
Executing install script for ksquirrel-R14.0.4-x86_64-1_tde.txz.
Package ksquirrel-R14.0.4-x86_64-1_tde.txz installed.

Script started, file is /tmp/kvpnc-build-log
Source 'kvpnc-R14.0.4.tar.bz2' not available yet...
Will download file to /local/src/bin/trinity/tde-slackbuilds-master-May25-2017/Apps/kvpnc
--2017-05-25 12:10:20--  http://mirror.ppa.trinitydesktop.org/trinity/releases/R14.0.4/applications/kvpnc-R14.0.4.tar.bz2
Resolving mirror.ppa.trinitydesktop.org (mirror.ppa.trinitydesktop.org)... 37.205.10.16
Connecting to mirror.ppa.trinitydesktop.org (mirror.ppa.trinitydesktop.org)|37.205.10.16|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://tde-mirror.yosemite.net/trinity/releases/R14.0.4/applications/kvpnc-R14.0.4.tar.bz2 [following]
--2017-05-25 12:10:21--  http://tde-mirror.yosemite.net/trinity/releases/R14.0.4/applications/kvpnc-R14.0.4.tar.bz2
Resolving tde-mirror.yosemite.net (tde-mirror.yosemite.net)... 172.110.30.91
Connecting to tde-mirror.yosemite.net (tde-mirror.yosemite.net)|172.110.30.91|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2566117 (2.4M) [application/x-bzip2]
Saving to: ‘/local/src/bin/trinity/tde-slackbuilds-master-May25-2017/Apps/kvpnc/kvpnc-R14.0.4.tar.bz2’

/local/src/bin/trin 100%[===================>]   2.45M  1.32MB/s    in 1.9s    

2017-05-25 12:10:24 (1.32 MB/s) - ‘/local/src/bin/trinity/tde-slackbuilds-master-May25-2017/Apps/kvpnc/kvpnc-R14.0.4.tar.bz2’ saved [2566117/2566117]

*** automake (GNU automake) 1.15 found.
*** Creating acinclude.m4
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating list of subdirectories
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
cd . && make -f admin/Makefile.common subdirs
make[2]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[2]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating configure.files
*** Creating configure.in
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
cd . && make -f admin/Makefile.common configure.in ;
make[2]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[2]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating aclocal.m4
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
acinclude.m4:6960: warning: the serial number must appear before any macro definition
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating configure
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating config.h template
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating Makefile templates
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
configure.in:43: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:43: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
doc/Makefile.am:6: error: required directory doc/tdeioslave does not exist
doc/Makefile.am:6: error: required directory doc/en does not exist
src/Makefile.am:91: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
admin/Makefile.common:10: recipe for target 'cvs' failed
make: *** [cvs] Error 1
Script done, file is /tmp/kvpnc-build-log
Cannot install /tmp/kvpnc-R14.0.4-*-1*.txz:  file not found

ls: cannot access '/var/log/packages/kvpnc-*R14.0.4-*-1*': No such file or directory

      Error:  kvpnc package build failed
      Check the build log /tmp/kvpnc-build-log
      
- ./BUILD-TDE.sh  9990.10s user 674.57s system 256% cpu 1:09:24.45 total

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Hey man. I will see if I can recreate this on my machine. I will do a fresh install in a little bit and setup Eric's multilib support. I haven't used it since I quit using steam so it's possible these updated scripts have never been tested on multilib.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I was unable to reproduce this error.
I installed Slackware64 14.2 full install then added Eric's mulitlib pkg's

I then compiled and installed ffmpeg and it's deps. (k9copy needs ffmpeg)

Afterwards I ran the BUILD-TDE script and built everything w/o international language support and everything went smoothly

**Comment by Thorn-Inurcide** [comment]
@Ndolam  Do you have ffmpeg? maybe a dep for it or it itself is required for the package as well?

**Comment by Thorn-Inurcide** [comment]
@Ndolam 

![snapshot1](https://cloud.githubusercontent.com/assets/10385564/26481040/238c0e8e-4193-11e7-9bde-41f0ed5be41f.png)

**Comment by Ndolam** [comment]
Thorn,
thanks for taking the time to run a build.

I do have ffmpeg (ffmpeg-3.1.1-x86_64-1alien) on that system, although the errors above didn't suggest to me that ffmpeg was an issue.  (And while I don't know where k9copy comes in, I did successfully build k9copy).

I hate to say this, but I now realize that, in fact, the machine I built it on is the one any only machine I have without the multi-lib stuff, it is a "pure" 64-bit system.

This isn't a show stopper for me, and if it works for you, perhaps it is just some peculiar thing on my system.  If you still have the build log file for kvpnc, would you mind posting it here, so that I can compare it to my build log, and maybe I can see what is broken on my system?

Thanks.

**Comment by Ray-V** [comment]
@Ndolam
Looks like this is the problem:

> doc/Makefile.am:6: error: required directory doc/tdeioslave does not exist  
> doc/Makefile.am:6: error: required directory doc/en does not exist  

The original doc/Makefile.am from the source archive is:

> KDE_LANG = "en de fr sv"  
> KDE_DOCS = kvpnc  
> SUBDIRS = $(AUTODIRS)  

and for an en-US only build this is overwritten by the SB script, lines 50-52, to give:

> KDE_LANG = en  
> KDE_DOCS = kvpnc  
> SUBDIRS = tdeioslave en  

If there are no 'tdeioslave en' directories in 'doc', go back to lines 38-42 in the SB - do you have an alias for 'rm' on your system which is removing the directories?

<hr>
Noticed this while looking at the above.

Moved the misc docs out of the 'doc' directory otherwise they end up in the html section, and forgot to add them back in when updating for the functions scripts:
```
--- Apps/kvpnc/kvpnc.SlackBuild
+++ Apps/kvpnc/kvpnc.SlackBuild
@@ -71,0 +72 @@
+mv ../tmpdocs/* $PKG${INSTALL_TDE}/doc/$PRGNAM-$VERSION

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
No problem. I do have the build log and yes you can have it. I didn't see anything about ffmpeg either but it was the only non official package besides Alien's multilib that I had installed so was just wondering. Looks like Ray-V was all over this though lol

Thanks @Ray-V 
[kvpnc-build-log.txt.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/1032782/kvpnc-build-log.txt.gz)

**Comment by Ndolam** [comment]
Thorn, thanks for the build log, but as you note...

Ray-V: you nailed it.   Thanks for looking into that.  When I rm'ed my own rm the package built without a hitch.

Cheers.
