### ISSUE TITLE
Dolphin defaults to KDE 4's terminal emulator

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#41]
dolphin is defaulting to KDE 4's emulator and I believe Ark as well. when KDE 4 is installed.

Not sure how to go about changing this as I saw no settings to alter the default terminal and archiver. Guess I will have to look through the makefile and source.

**Comment by Thorn-Inurcide** [comment]
```
void Dolphin::openTerminal()
{
    TQString command("konsole --workdir \"");
    command.append(m_activeView->url().path());
    command.append('\"');

    KRun::runCommand(command, "Konsole", "konsole");
}

**Comment by Thorn-Inurcide** [comment]
So in the source code for dolphin I found the above code. sadly both KDE4 and TDE have that named konsole. I can't legitimately rename the konsole binary without going through an astronomical amount of TDE source code. I was thinking I could create a patch that uses the INSTALL_TDE prefix to change this too  INSTALL_TDE/konsole --workdir to direct to to the prefixed path directly. And could have the patch applied only if TDE is installed outside of /usr (If it's installed in /usr KDE4 probably isn't on the users system) I will still need to view the rest of Dolphins code to check for more instances of Konsole being invoked and hunt down ark and do the same. @Ray-V  what do you think?

**Comment by Thorn-Inurcide** [comment]
/usr/share/bin probably shows up in a users search path before say /opt/trinity/bin. i'm guessing I could bump this path but then inside KDE4 it might cause problems. Plus that's a user change , something the SlackBuild wouldn't handle. (or maybe I'm wrong?? which would be awesome cause that would make this a quick fix) I feel like that would be invasive though

**Comment by Thorn-Inurcide** [comment]
I'll just start work on a patch. it shouldn't be too hard. Most time consuming part will be removing TDE and compiling it all again into /opt after reinstalling kde4

**Comment by Ndolam** [comment]
Well, you know, there are only 2807 placed with "Konsole" or "konsole"
in the current TDE distribution.  Too many to do by hand, but doesn't
it *almost* make you want to do (untested):

cd <the directory above wherever your previous run put "src">
rm -rf TMP
for i in src/*.bz2
do
    (
       mkdir TMP
       cd TMP
       tar xf ../$i
       find . -type f -print0 \
          | xargs -0 sed -i -e 's/konsole/tonsole/g' -e 's/Konsole/Tonsole/g'
       for i in `find . -name \*[Kk]onsole\* -print0`
       do
          mv $i `echo $i | sed -e 's/konsole/tonsole/g' -e 's/Konsole/Tonsole/g'`
       done
       tar cfj ../$i .
    )
done
rm -rf TMP

and then see what happens?



You know you want to try this, don't you?  :-)

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
this sounds awesome in theory man lol

My biggest concern is this would have to be forcefully done, through the BUILD-TDE.sh/get-source.sh scripts and would mean that the user would need all the tarballs predownloaded. 

I believe the simplest way to go about this would be a patch just for Dolphin that directs dolphin to look for konsole in INSTALL_TDE/bin/konsole. Theres not too much source code in dolphin and I can just search for instances of konsole/Konsole with the IDE

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I might have to rename it all. It appears when I right click on the desktop that opens KDE4's konsole as well

**Comment by Thorn-Inurcide** [comment]
Man theres got to be an easier way around this

**Comment by Thorn-Inurcide** [comment]
@SlavekB 
Was wondering if you would have an idea as to why when KDE4 is installed TDE is opening it's version of Konsole and attempting to use KDE4s ark as well? I'm stuck on this. Was going to patch Dolphin until I realized it's happening from the desktop as well.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Using your idea but the find command found in koffice to rename chalk to krita provided by Ray-V
I was able to easily change konsole to tonsole. I could apply this to the slackbuilds that contain use of konsole and change them all to tonsole. then i'll have to chage ark to something.

**Comment by Ndolam** [comment]
Thorn: That could (assuming it works) could probably be added to the place in the SlackBuild where the .bz2 files are unpacked, and that would actually be easier than unpacking, modifying, and repacking.

And that way, each source tar could be modified only if and when it is downloaded.

Further, by turning it into a function with parameters, it could rename not only konsole, but other
things are well

    # Call this function after expanding a source tar file.
    # Args: an even number of strings (considered as pairs (s,r)),
    # where s is a regular expression to search for and r is the
    # replacement text.
    # It is the callers job to cd to the appropriate dir before
    # calling this function, as in
    #    tar xf .../some-tar-file
    #    cd top-level dir of that tar file
    # If the tar file unpacks into multiple directories, a bit harder
    # thinking will be required :-)
    rename ()
    {
	if [ `expr $# / 2` -ne 0 ]
	then
	    echo >&2 "rename: you screwed up by giving an odd # of args!"
	    exit 1
	fi
	while [ $# -gt 1 ]
	do
	    s="$1"
	    r="$2"
	    shift ; shift
	    if echo "$s $r" | grep "[^\]@" >/dev/null
	    then
		echo >&2 "You can an unescaped @ in your regexp."
		echo >&2 "I can't handle that.  You deal with it."
		exit 2
	    fi
	    
	    find . -type f -print0 | xargs -0 sed -i "s@$s@$r@g"
	done
    }

    # A second function with analogous pairs of arguments to rename files
    # except the first arg is a plain string, not a regexp.
    move ()
    {
	if [ `expr $# / 2` -ne 0 ]
	then
	    echo >&2 "move: you screwed up by giving an odd # of args!"
	    exit 1
	fi
	while [ $# -gt 1 ]
	do
	    old="$1"
	    new="$2"
	    shift ; shift
	    if echo "$old $new" | grep "[^\]@" >/dev/null
	    then
		echo >&2 "You can an unescaped @ in your regexp."
		echo >&2 "I can't handle that.  You deal with it."
		exit 2
	    fi
            for i in `find . -name "$old"`
	    do
		mv $i `echo $i | sed -e 's@$old@$new@g'`
	    done
	done
    }

    # Sample uses
    rename konsole tdeterm Konsole Tdeterm
    move konsole tdeterm Konsole Tdeterm

Beware: these are completely and utterly untested.  ("What could possibly go wrong?" -- Calvin)

**Comment by Ndolam** [comment]
With the above functions, you could write

    replace "\<ark\>" arc

which would only replace "ark" when it is a "token". as in

    $ echo "ark bark arking bookmark ark" | sed 's/\<ark\>/arc/g' 
    arc bark arking bookmark arc

I'm not sure this gets exactly all the substitutions you want (nothing more and nothing less), but
it might be worth considering.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 

quick question.. do you have kde4 and trinity installed?

I removed and tried another /usr build to check some things.

my friend gave me an idea and a temp work around.  Symlink TDE's konsole and ark to /usr/local/bin and see if that make it work right

Don't know how this will effect KDE4 though. hopefully it won't

**Comment by Ndolam** [comment]
Thorn, I do have kde4 installed alongside trinity.
When I run dl3phin and then start a konsole from there, I get trinity's konsole.
I take it from this thread that you are not getting that.

Having said that, my PATH has /opt/trinity/bin *before* /usr/bin, and that may be the issue.
What is your PATH?

**Comment by Thorn-Inurcide** [comment]
Opt/trinity is last in my path
Sent using Zoho Mail


---- On Fri, 21 Jul 2017 13:10:44 -0700  notifications@github.com wrote ----

Thorn, I do have kde4 installed alongside trinity.
When I run dl3phin and then start a konsole from there, I get trinity's konsole.
I take it from this thread that you are not getting that.

Having said that, my PATH has /opt/trinity/bin before /usr/bin, and that may be the issue.
What is your PATH?

**Comment by Ndolam** [comment]
OK.  Using strace -f -e trace=process d3lphin and then looking at the output, I see
[pid 12551] execve("/bin/sh", ["/bin/sh", "-c", "konsole --workdir \"/home/me\" "], [/* 68 vars */]) = 0
[pid 12551] arch_prctl(ARCH_SET_FS, 0x7f38c6d00700) = 0
[pid 12551] execve("/opt/trinity/bin/konsole", ["konsole", "--workdir", "/home/me"], [/* 65 vars */]) = 0
and so you can see that since dolphin is calling sh to exec konsole, it is going to honour your path.
Or so it seems to be after an exhaustive (30 second :-) analysis.
I guess you want to fix your PATH?

**Comment by Thorn-Inurcide** [comment]
Did you manually change your PATH because its always installed its PATH at the end of my current PATH? I can adjust it just wondering if you had too or if it just installed like thatfor you
Sent using Zoho Mail


---- On Fri, 21 Jul 2017 13:25:57 -0700  notifications@github.com wrote ----

OK. Using strace -f -e trace=process d3lphin and then looking at the output, I see
[pid 12551] execve("/bin/sh", ["/bin/sh", "-c", "konsole --workdir "/home/me" "], [/* 68 vars /]) = 0
[pid 12551] arch_prctl(ARCH_SET_FS, 0x7f38c6d00700) = 0
[pid 12551] execve("/opt/trinity/bin/konsole", ["konsole", "--workdir", "/home/me"], [/ 65 vars */]) = 0
and so you can see that since dolphin is calling sh to exec konsole, it is going to honour your path.
Or so it seems to be after an exhaustive (30 second :-) analysis.
I guess you want to fix your PATH?

**Comment by Thorn-Inurcide** [comment]
@Ndolam Thanks for the feedback 
I'm going to marked this closed and make note in KNOWN-ISSUES that if this comes up to just adjust the $PATH

**Comment by Ndolam** [comment]
Thorn: no problem.  

I manually set my PATH in my shell init files.
I've been doing that for a long time, it solves way more problems (for me) than it creates.

Cheers.
