### ISSUE TITLE
Question about translations

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#47]
@Ray-V 

I've added some new packages to TDE that can be compiled. I was looking at builds you made and then looking for PO files in the source of the ones I added. And some have specific files and then i just looked in kvkbd and its po folder just has a makefile that says POFILES = AUTO and it compiled with no support for es which i have my install setup for (I didn't attempt to manually add support) And then with say, krusader it built with all the languages the the program has po files for.

So I guess my question is, would i manually remove translations from the programs that build more than selected (ex krusader) ? Is this what's going on , am I looking at your comments right?

and i have no idea how to approach the kvkbd. Can the chosen languages at build time be forced into it?

**Comment by Ray-V** [comment]
kvkbd has a po folder, but no .po files in it, so you'd have to set up your own es.po if you want a Spanish translation.

krusader has a similar i18n structure to ksquirrel, so for selective i18n support, using the i18n section in ksquirrel.SB as a template works.
Only English and Russian html docs are available, so that simplifies the help documents test.

```diff
--- Apps/krusader/krusader.SlackBuild
+++ Apps/krusader/krusader.SlackBuild
@@ -37,0 +38,10 @@
+# set support for additional language(s) as per I18N variable
+# but only for languages available with this package
+langs="";for Lang in $I18N;do [[ -e po/$Lang".po" ]] && langs="$langs $Lang"".po";done
+sed -i "s|POFILES =.*$|POFILES =$langs|" po/Makefile.am
+langs=$(echo $langs | sed 's|.po||g')
+
+# Only Russian and English help documents are in the source,
+# if Russian is not required, only package English docs
+[[ $I18N != *ru* ]] && sed -i "s| ru||" doc/Makefile.am
+
@@ -79 +89 @@
-$PRGNAM:
+$PRGNAM: With language support for:
@@ -81 +91 @@
-$PRGNAM:
+$PRGNAM: en $langs
```

<hr>
BTW Did you ever get your friend to check the translations in the es.po I set up for knights?

**Comment by Ray-V** [comment]
**kvkbd** - es.po

The easiest way to set up a .po file is to base it on a template, .pot, or an existing .po, but there aren't any for kvkbd.

Next best is to edit any other existing .po file in a text editor or use kbabel.

[1] find the i18n strings in the source code to show which phrases are translatable: 

`grep -ir i18n applications/kvkbd/*`

\- only the last three lines relate to the source code:

>applications/kvkbd/src/main.cpp:    I18N_NOOP("A virtual keyboard for TDE");  
>applications/kvkbd/src/main.cpp: { "loginhelper", I18N_NOOP("Stand alone version for use with TDM or XDM. \nYou should Add : HOME=/root kvkbd --loginhelper & to Xsetup to run in xdm/tdm"), 0 },  
>applications/kvkbd/src/main.cpp:    TDEAboutData about("kvkbd", I18N_NOOP("kvkbd"), version, description,

[2] get translations for the I18N_NOOP strings [could also be i18n("\<phrase\>") - but there aren't any in this source] - I used Google translate

[3] use an existing .po file as a template - for three lines use a text editor:
```
msgid ""
msgstr ""
"Project-Id-Version: kvkbd-R14.0.4\n"
"Report-Msgid-Bugs-To: TI@example.com\n"
"PO-Revision-Date: 2017-08-05\n"
"Last-Translator: TI <TI@example.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: /src/main.cpp
msgid "A virtual keyboard for TDE"
msgstr "Un teclado virtual para TDE"

#: /src/main.cpp
msgid "Stand alone version for use with TDM or XDM. \nYou should Add : HOME=/root kvkbd --loginhelper & to Xsetup to run in xdm/tdm"
msgstr "Versión autónoma para uso con TDM o XDM. \nUsted debe agregar: HOME=/root kvkbd --loginhelper & a Xsetup para ejecutar en xdm/tdm"

#: /src/main.cpp
msgid "kvkbd"
msgstr "kvkbd"
```
and save to es.po in Apps/kvkbd and patch kvkdb.SB as per knights.SB:

```diff
--- Apps/kvkbd/kvkbd.SlackBuild
+++ Apps/kvkbd/kvkbd.SlackBuild
@@ -28 +28 @@
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
@@ -37,0 +38,9 @@
+# the included es.po file is a Google translation - if you're happy to use it ..
+cp $SRCDIR/es.po po || true
+#
+# set support for additional language(s) as per I18N variable
+# but only for languages available with this package
+langs="";for Lang in $I18N;do [[ -e po/$Lang".po" ]] && langs="$langs $Lang"".po";done
+sed -i "s|POFILES =.*$|POFILES =$langs|" po/Makefile.am
+langs=$(echo $langs | sed 's|.po||g')
+
@@ -79 +87,0 @@
-$PRGNAM:
@@ -81,0 +90 @@
+$PRGNAM: With language support for: en $langs
```

There is no meaningful en html documentation to be translated - what there is is just a placeholder.

From the konsole, `kvkbd --help` then gives
```
Modo de uso: kvkbd [opciones-Qt] [opciones-TDE] [opciones]

Un teclado virtual para TDE

Opciones genéricas:
  --help                    Mostrar ayuda sobre las opciones
  --help-qt                 Mostrar las opciones específicas de Qt
  --help-tde                Mostrar las opciones específicas de TDE
  --help-all                Mostrar todas las opciones
  --author                  Mostrar información sobre el autor
  -v, --version             Mostrar información de la versión
  --license                 Mostrar información de la licencia
  --                        Fin de las opciones

Opciones:
  --loginhelper             Versión autónoma para uso con TDM o XDM.
                            Usted debe agregar: HOME=/root kvkbd --loginhelper & a Xsetup para ejecutar en xdm/tdm
```

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Thank you for all the help and information. =] I'll try to do the others myself.


BTW Did you ever get your friend to check the translations in the es.po I set up for knights? 

I did not, I left Arizona after only a month. I made the mistake of going to Tucson instead of going back to Phoenix and I hated it, Ended up back in Cleveland for a bit. I'm leaving next Saturday for Phoenix. ( i've been in AR for the last 3 months over a family illness/death) I'll be back in AZ next week, and once I have internet setup and everything I'll get it looked it. Thank you for reminding me because I forgot

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I'm not too hard up on creating a bunch of .po files for kvkbd (or any others really) I am just compiling with es support during build time for testing purposes.  I was hoping it could just be forced in there but it cannot =] I'll add the es support for kvkbd since you already created it though =]

**Comment by Thorn-Inurcide** [comment]
@Ray-V 

In response to my earlier reply to your knights question, I was just asked to stay out here until October 2,
So my trip to Phoenix may be getting postponed =[ 

I'm going to make a note to remind self about it though so I don't forget again.
